services:
  - type: web
    name: shopflow-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod,render
      - key: JWT_SECRET
        generateValue: true
      - key: APP_MAIL_ENABLED
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        value: https://shopflow-api.onrender.com
      - key: DB_HOST
        fromDatabase:
          name: shopflow-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: shopflow-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: shopflow-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: shopflow-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: shopflow-db
          property: password

databases:
  - name: shopflow-db
    plan: free
    databaseName: ecommerce
    user: ecommerce
