ALTER TABLE products ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    title           VARCHAR(50) NOT NULL,
    full_name       VARCHAR(120) NOT NULL,
    phone           VARCHAR(20) NOT NULL,
    city            VARCHAR(80) NOT NULL,
    district        VARCHAR(80) NOT NULL,
    address_line    VARCHAR(300) NOT NULL,
    postal_code     VARCHAR(10),
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_addresses_user ON addresses(user_id);

ALTER TABLE orders ADD COLUMN shipping_full_name VARCHAR(120);
ALTER TABLE orders ADD COLUMN shipping_phone VARCHAR(20);
ALTER TABLE orders ADD COLUMN shipping_city VARCHAR(80);
ALTER TABLE orders ADD COLUMN shipping_district VARCHAR(80);
ALTER TABLE orders ADD COLUMN shipping_address_line VARCHAR(300);
ALTER TABLE orders ADD COLUMN shipping_postal_code VARCHAR(10);
